language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update 
  - sudo apt-get install -qq libopencv-dev libeigen2-dev

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release 

script: make
